
#**Laboratorio #2 (6%)**

**Instrucciones:** El presente trabajo consta de seis (6) problemas cada uno con un valor determinado. La entrega del laboratorio **debe ser realizada en grupos de máximo 4 integrantes**. Se debe entregar un **solo documento por grupo** en el cual **debe aparecer de forma clara los nombres completo de los integrantes**. Por favor, **comentar de forma organizada y coherente** los pasos realizados.  

**Formato de entrega:** Para la entrega de este trabajo, descargue el archivo en **formato PDF** (esto lo consigue con la combinación de teclas **ctrl + p** y guardando el archivo en el formato requerido) y enviarlo a través de Interactiva en el buzón designado para ello.

**NOTA:** No olvide imprimir las respuestas de sus cálculos.

In [ ]:
########---------------Nombre completo de los integrantes del grupo de trabajo-------------------##########

# Integrante 1: Alexandra Hurtado David

# Integrante 2: Mariana Valderrama Castañeda

# Integrante 3:

# Integrante 4:

### **Ejercicio #1: (0.6)**
Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 -k & k-1 & k+1 & k & 0\\
1 & 2 & 3 & 4 & 1\\
2-k & k+3 & k+7 & 2 & 1 \\
-2 & 3 & 4 & 6 & 2 \\
0 & 2 & 1 & 0 & 3
\end{pmatrix}.
\end{equation*} \


a). **(0.3)**  Halle los valores de $k$ para los cuales la matriz $A$ tiene inversa.

b). **(0.3)**  Halle los valores de $k$ para los cuales $\det(A) = k -4$.


In [ ]:
# Solución Ejercicio 1. (No olvide imprimir las respuestas de sus cálculos)

# (a):


In [ ]:
# Solución Ejercicio 1. (No olvide imprimir las respuestas de sus cálculos)

# (b):


### **Ejercicio #2: (0.7)**
Sean $A(x_1,y_1), \ B(x_2,y_2)$ y $C(x_3,y_3)$ tres puntos en el plano $xy$. El área del triángulo formado por dichos puntos $A,B,C$ es dada por la expresión  

\begin{equation*}
 \mbox{Área} = \frac{1}{2} \left | \det
\begin{pmatrix}
x_1 & y_1 & 1\\
x_2 & y_2 & 1 \\
x_3 & y_3 & 1
\end{pmatrix} \right|,
\end{equation*}

donde el símbolo $|.|$ denota el valor absoluto.

a). **(0.3)** Sean $A(0,-3), \ B(8,1)$ y $C(-2,5)$. Halle el área del triángulo formado por los puntos $A, \ B, \ C$.  

b). **(0.4)**  ¿Para qué valores de $k$ el **cuadrado del área del triángulo** formado por los puntos $A(1,k), \ B(k,0)$ y $C(0,k)$ es igual al área encontrada en el item (a)?

In [9]:
# Solución Ejercicio 2. (No olvide imprimir las respuestas de sus cálculos)
import sympy as sp
# (a):
u=0.5
matriz = sp.Matrix([[0, -3, 1 ],
                    [8, 1, 1],
                    [-2,  5, 1]])
determinante= matriz.det()
area =u*determinante
print(area)








36.0000000000000


In [8]:
# Solución Ejercicio 2. (No olvide imprimir las respuestas de sus cálculos)

# (b):
u=0.5
k = sp.Symbol('k')
matrizA= sp.Matrix([[0, -3, 1 ],
                    [8, 1, 1],
                    [-2,  5, 1]])
matrizB = sp.Matrix([[1, k, 1 ],
                    [k, 0, 1],
                    [0,  k, 1]])

determinanteA= matrizA.det()
areaA =u*determinanteA

determinanteB= matrizB.det()
areaB =u*determinanteB


# el areaB**2-AreaA da 0 al ser iguales y resuelvo la ecuación para k
Sol = sp.solve(areaB**2 - areaA, k)
print(Sol)


[-12.0000000000000, 12.0000000000000]


### **Ejercicio #3: (0.7)**
Considere el conjunto de vectores de $\mathbb{R}^6$:

$$ S = \{ (1,0,1,0,0,0), (0,1,0,1,0,1), (-1,1,0,0,1,1), (0,0,-1,-1,1,-1),(-1,0,-2,0,1,0), (0,0,0,1,-1,1)\}.     $$

(a). **(0.3)** Muestre que dicho conjunto $S$ es una base para $\mathbb{R}^6$.

(b). **(0.4)** Determinar las coordenadas del vector $(1, 2, 3,4,5,5)$ en dicha base.

In [ ]:
# Solución Ejercicio 3. (No olvide imprimir las respuestas de sus cálculos)

# (a):


In [ ]:
# Solución Ejercicio 3. (No olvide imprimir las respuestas de sus cálculos)

# (b):

### **Ejercicio #4: (1.0)**
Considere el espacio vectorial

$$ M_{n \times n}(\mathbb{R}) := \left\lbrace \begin{equation*}
 A =
\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
\end{equation*} :  a_{ij} \in \mathbb{R}, \  ∀ i,j = 1,...,n  \right\rbrace,$$

es decir, el espacio de las matrices cuadradas de tamaño $n \times n$ con las operaciones usuales de las matrices.
Si $A$ y $B$ están en $M_{n \times n}(\mathbb{R})$, se define el producto escalar y la norma como sigue:

$$  \langle A,B \rangle = Tr(B^{T}A), \quad \quad \|A\|  = \sqrt{Tr(A^{T}A)},          $$
donde $Tr(A)$ denota la traza de la matriz $A$, y se define como $Tr(A) = a_{11} + a_{22} + \cdots + a_{nn}.$

  a). **(0.5)** Sea $n = 4$ y considere las matrices \begin{equation*}
  A =
  \begin{pmatrix}
  1 &  0 & 3 & 20\\
  0 & 1 & 2 & 5 \\
-4 & 6 & 1 & -9 \\
7 & 2 & 1 & 0
  \end{pmatrix}, \
  B =
  \begin{pmatrix}
   8 &  6 & 14 & 2\\
  1 & 0 & 3 & 0 \\
5 & 8 & 1 & 9 \\
-3 & -3 & 1 & 1
  \end{pmatrix},
  \end{equation*} halle $-3 \langle AB,B \rangle -  \| A^2-B^2 \|$.  



b). **(0.5)**  Halle **la mitad del  ángulo** entre las matrices $A$ y $B$ definidas anteriormente (dar su respuesta en grados).



In [10]:
#########---------- Ejecutar esta parte antes de dar respuesta a las preguntas-----------#########

# NOTA: El producto escalar aqui definido puede calcularse  mediante la siguiente función:

import numpy as np

Product = lambda A,B: np.trace(np.transpose(B) @ A)

# Dicha función recibe como entradas las matrices A,B y devuelve como resultado el producto escalar de A y B.

# Ejemplo: Hallemos el producto escalar <A,B> con las matrices definidas a continuación

A = np.array([[9, 0, 0, 0],[0,2,0,0],[0,0,3,0],[0,0,0,1]])

B = np.array([[1, 0, 0, 0],[0,3, 0, 0],[0, 0, 4, 0],[0, 0, 0, 2]])

Sol = Product(A,B)

print('Sol =', Sol)

Sol = 29


In [25]:
# Solución Ejercicio 4. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas la función antes definida

# (a):
import numpy as np

A = np.array([[1, 0, 3, 20],
              [0, 1, 2, 5],
              [-4, 6, 1, -9],
              [7, 2, 1, 0]])

B = np.array([[8, 6, 14, 2],
              [1, 0, 3, 0],
              [5, 8, 1, 9],
              [-3, -3, 1, 1]])

# Calculo AB
AB = np.dot(A, B)

#  el producto escalar <AB, B>
producto = lambda AB,B: np.trace(np.transpose(B) @ AB)
producto_escalar = producto(AB, B)

# A^2 y B^2
Aalcuadrado = np.dot(A, A)
Balcuadrado = np.dot(B, B)

# Paso 4: Calcular la norma ||A^2 - B^2||
norma = np.sqrt(np.trace(np.dot(Aalcuadrado - Balcuadrado, np.transpose(Aalcuadrado - Balcuadrado))))

# Paso 5: Calcular -3<AB, B> - ||A^2 - B^2||
result = -3 * producto_escalar- norma

# Resultado
print("Resultado:", result)


Resultado: -187.12575184235118


In [20]:
# Solución Ejercicio 4. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas la función antes definida

# (b):
import numpy as np

# Definir matrices A y B
A = np.array([[1, 0, 3, 20],
              [0, 1, 2, 5],
              [-4, 6, 1, -9],
              [7, 2, 1, 0]])

B = np.array([[8, 6, 14, 2],
              [1, 0, 3, 0],
              [5, 8, 1, 9],
              [-3, -3, 1, 1]])

# Producto escalar <A, B>

producto = lambda A,B: np.trace(np.transpose(B) @ A)
producto_escalar = producto(A, B)

# Normas A y B
norma_A = np.sqrt(np.trace(np.dot(np.transpose(A), A)))
norma_B = np.sqrt(np.trace(np.dot(np.transpose(B), B)))

# Coseno del ángulo
cos_theta = producto_escalar / (norma_A * norma_B)

# Ángulo en radianes
theta_radianes = np.arccos(cos_theta)

# Convertir el ángulo a grados
theta_grados = np.degrees(theta_radianes)


mitad_angulo = theta_grados / 2


print("La mitad del ángulo entre A y B es:", mitad_angulo, "grados")


La mitad del ángulo entre A y B es: 44.08052267492063 grados


### **Ejercicio #5: (1.0)**
Considere el conjunto

$$ \mathbb{R}^{2} := \{ \vec{u} = (u_1,u_2):  u_{1},u_{2} \in \mathbb{R} \}.$$

Para  $\vec{u} = (u_1,u_2)$, $\vec{v} = (v_1,v_2)$ en  $\mathbb{R}^{2}$ y $\alpha \in \mathbb{R}$ se definen  las operaciones:

$$\vec{u} \oplus \vec{v} := (u_1 + v_1 + 2,u_2 + v_2 + 2),$$

$$ \alpha \odot \vec{u} := (\alpha + \alpha u_1 -1,\alpha + \alpha u_2 -1).   $$

a). **(0.5)** Halle $  6 \odot (8,2) \oplus 3 \odot (-1,18). $

b). **(0.5)** Muestre que el vector $\vec{0} = (-2,-2)$ es el elemento neutro aditivo verificando la igualdad $\vec{0} \oplus (4,6) = (4,6).$


In [ ]:
#########---------- Ejecutar esta parte antes de dar respuesta a las preguntas-----------#########

# NOTA: Las operaciones suma y producto aqui definidas pueden ser calculadas  mediante las siguientes funciones:

SUMA = lambda u,v:  np.array([[u[0,0] + v[0,0] + 2,u[0,1] + v[0,1] + 2]])

# La función SUMA recibe como entradas los vectores u,v y devuelve como resultado la suma de dichos vectores.

PRODUCTO = lambda alpha,u:  np.array([[alpha + alpha*u[0,0] - 1,alpha + alpha*u[0,1] - 1]])

# La función PRODUCTO recibe como entradas el escalar alpha y el vector u, y devuelve como resultado el producto escalar de alpha por u.

# Ejemplo: Hallemos la suma de u = (2,7) con v = (0,4).

u = np.array([[2, 7]])

v = np.array([[0, 4]])

Sol = SUMA(u,v)

print('Sol =', Sol)


Sol = [[ 4 13]]


In [ ]:
# Solución Ejercicio 5. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas las funciones antes definida

# (a):

In [ ]:
# Solución Ejercicio 5. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas las funciones antes definida

# (b):

### **Ejercicio #6: (1.0)**
Considere el espacio vectorial $M_{2 \times 2}(\mathbb{R})$ dotado del producto escalar definido en el **Ejercicio # 4**.  Use el proceso de **Gram-Schmidt** para construir una base ortonormal para el subespacio de $M_{2 \times 2}(\mathbb{R})$  generado por la base

\begin{equation*}
  A_1 =
  \begin{pmatrix}
  -1  & 3\\
0  &  1
  \end{pmatrix}, \
  A_2 =
  \begin{pmatrix}
   1 &  2\\
-1 & 0
  \end{pmatrix},
  \
  A_3 =
  \begin{pmatrix}
   -2 &  0\\
1 & 1
\end{pmatrix},
  \end{equation*}

In [26]:
import numpy as np

# Definimos las matrices A1, A2, A3 (correspondientes a u1, u2, u3 en tu ejemplo)
A1 = np.array([[-1, 3], [0, 1]])
A2 = np.array([[1, 2], [-1, 0]])
A3 = np.array([[-2, 1], [1, 1]])

# Definimos la función del producto escalar como la traza de la multiplicación de matrices
Product = lambda A, B: np.trace(np.transpose(B) @ A)

# Hallamos el vector v1 (equivalente a u1 en el ejemplo)
v1 = A1

# Hallamos el vector v2
producto_v1_v1 = Product(v1, v1)
producto_u2_v1 = Product(A2, v1)

v2 = A2 - (producto_u2_v1 / producto_v1_v1) * v1

# Hallamos el vector v3
producto_v2_v2 = Product(v2, v2)
producto_u3_v1 = Product(A3, v1)
producto_u3_v2 = Product(A3, v2)

v3 = A3 - (producto_u3_v1 / producto_v1_v1) * v1 - (producto_u3_v2 / producto_v2_v2) * v2


v1_normal = v1 / np.sqrt(Product(v1, v1))
v2_normal = v2 / np.sqrt(Product(v2, v2))
v3_normal = v3 / np.sqrt(Product(v3, v3))

# Imprimimos los vectores ortonormales
print('v1 ortonormal =\n', v1_normal)
print('\nv2 ortonormal =\n', v2_normal)
print('\nv3 ortonormal =\n', v3_normal)



v1 ortonormal =
 [[-0.30151134  0.90453403]
 [ 0.          0.30151134]]

v2 ortonormal =
 [[ 0.75341057  0.32961713]
 [-0.51796977 -0.2354408 ]]

v3 ortonormal =
 [[-0.75592895  0.37796447]
 [ 0.37796447  0.37796447]]
