
# **Guía #4: Determinante e inversa de una  matriz**

**Objetivo:** Usar el lenguaje de programación de Python para ejecutar el calculo de la inversa y el determinante de matrices.

**Temas:** Dentro de los temas que se estarán tratando están inversa de matrices y determinantes.




**Ejemplo 1:** Despejar $X$ en las ecuaciones matriciales.

(a). $XAB^{T} = AB^{T} + XC^2,$ donde

\

\begin{equation*}
 A =
\begin{pmatrix}
1 & 2\\
-1 & 0\\
1 & -1
\end{pmatrix}, \
B =
\begin{pmatrix}
0 & -1\\
1 & 1\\
3 & 0
\end{pmatrix}, \
C =
\begin{pmatrix}
0 & 1 & 0\\
1 & 0 & 1\\
0 & 1 & 0
\end{pmatrix}.
\end{equation*} \


(b). $AX -3I -4X = C,$ donde

\

\begin{equation*}
 A =
\begin{pmatrix}
1 & 2 & 0\\
0 & 1 & 2\\
0 & 0 & 1
\end{pmatrix}, \  
C =
\begin{pmatrix}
2 & -2 & 1\\
1 & 1 & -2\\
3 & 0 & 4
\end{pmatrix}.
\end{equation*}


In [ ]:
# Solución Ejemplo 1.

# (a):

# Importamos la biblioteca numpy con el alias np.
import numpy as np

# Definimos las matrices A, B y C

A = np.array([[1, 2],[-1, 0],[1, -1]])

B = np.array([[0, -1],[1, 1],[3, 0]])

C = np.array([[0, 1, 0],[1, 0, 1],[0, 1, 0]])


# Hallo la matriz X = (AB^T)((AB^T) - C^2)^-1

BT =  np.transpose(B)

X = (A @ BT) @ np.linalg.inv(A @ BT - C @ C)

# Imprimo la matriz X

print('X =', X)

X = [[ 0.66666667 -0.33333333  0.33333333]
 [ 0.          0.33333333 -1.        ]
 [-0.33333333 -0.33333333  1.33333333]]


In [ ]:
# Solución Ejemplo 1.

# (b):

# Definimos las matrices A y C

A = np.array([[1, 2, 0],[0, 1, 2],[0, 0, 1]])


C = np.array([[2, -2, 1],[1, 1, -2],[3, 0, 4]])


# Hallo la matriz X = ((A-4I)^-1)(C+3I)

I = np.eye(3)

X = np.linalg.inv(A - 4*I) @ (C + 3*I)

# Imprimo la matriz X

print('X =', X)


X = [[-2.33333333 -0.22222222 -0.92592593]
 [-1.         -1.33333333 -0.88888889]
 [-1.          0.         -2.33333333]]


**Ejemplo 2:** Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 k + 1 & 0 & 1\\
1 & -1 & 2\\
10 & k & -1
\end{pmatrix}.
\end{equation*} \

(a). Halle los valores de $k$ para los cuales la matriz $A$ no tiene inversa.

(b). Halle los valores de $k$ para los cuales la matriz $A^2 + 3A$ no tiene inversa.

In [ ]:
# Solución Ejemplo 2.

# (a):

# Llamamos el entorno sympy para trabajar con cálculos simbólicos.

import sympy as sp

# Defino la variable "k" y creo la matriz A.

k = sp.Symbol('k')

A = sp.Matrix([[k+1,0, k], [1,-1, 2],[10, k, -1]])

# Hallo el determinante de la matriz A.

det_A = A.det()

# Resuelvo la ecuación det_A = 0 en términos de k.

Sol = sp.solve(det_A, k)

# Imprimo las soluciones

print('Sol =', Sol)

Sol = [9/2 - sqrt(85)/2, 9/2 + sqrt(85)/2]


Por lo tanto, para los valores de $k = \frac{9 \pm \sqrt{85}}{2}$ la matriz A no posee inversa ya que su determinante es cero.

In [ ]:
# Solución Ejemplo 2.

# (b):

B = A**2 + 3*A

# Hallo el determinante de la matriz B.

det_B = B.det()

# Resuelvo la ecuación det_B = 0 en términos de k.

Sol = sp.solve(det_B, k)

# Imprimo las soluciones

print('Sol =', Sol)

Sol = [-12 + 4*sqrt(10), 9/2 - sqrt(85)/2, 9/2 + sqrt(85)/2, -4*sqrt(10) - 12]


Por lo tanto, para los valores de $k = \frac{9 \pm \sqrt{85}}{2}, \ -12 \pm 4\sqrt{10}$ la matriz $A^2 + 3A$ no posee inversa ya que su determinante es cero.

**Ejemplo 3:** Considere las matrices

\begin{equation*}
 A =
\begin{pmatrix}
 1 & -1 & 2\\
x-1 & 0 & x+3\\
1 & x-2 & 4
\end{pmatrix},\ \
B =
\begin{pmatrix}
 x & 3 & 1\\
x+1 & 4 & 2\\
x & 2-x^2 & 1
\end{pmatrix}.
\end{equation*} \

(a). Resolver la ecuación $det(A) = 1 -7x$.

(b). Resolver la ecuación $det(B) = x^3 - 1$.


In [ ]:
# Solución Ejemplo 3.

# (a):

# Defino la variable "x" y creo la matriz A.

x = sp.Symbol('x')

A = sp.Matrix([[1,-1, 2], [x-1,0, x+3],[1, x-2, 4]])

# Hallo el determinate de la matriz A.

det_A = A.det()

# Resuelvo la ecuación det_A + 7x - 1 = 0 en términos de x.

Sol = sp.solve(det_A + 7*x -1, x)

# Imprimo las soluciones

print('Sol =', Sol)

Sol = [-2, -1]


En consecuencia, los valores de $x$ son $-1$ y $-2$.

In [ ]:
# Solución Ejemplo 3.

# (b):

# Creo la matriz B. Note que x^2 se escribe como x**2.

B = sp.Matrix([[x,3, 1], [x+1,4, 2],[x, 2-x**2, 1]])

# Hallo el determinate de la matriz B.

det_B = B.det()

# Resuelvo la ecuación det_B - x^3 + 3 = 0 en términos de x.

Sol = sp.solve(det_B - x**3 + 1, x)

# Imprimo las soluciones

print('Sol =', Sol)

Sol = [0, 1]


Luego, los valores de $x$ son $0$ y $1$.

**Ejemplo 4:** Considere las matriz

\begin{equation*}
 A =
\begin{pmatrix}
 1 & -1 & 0\\
-1 & 1 & 0\\
-4 & -2 & 1
\end{pmatrix}.
\end{equation*} \

Determinar los valores de $\lambda$ tales que $det(A-\lambda I) = 0$.



In [ ]:
# Solución Ejemplo 4.


# Defino la variable "lambda" y creo la matriz B = A-lambda*I.

Lambda = sp.Symbol('Lambda')

A = sp.Matrix([[1,-1, 0], [-1,1,0],[-4, -2, 1]])

I = np.eye(3)

B = A-Lambda*I

# Hallo el determinante de la matriz B.

det_B = B.det()

# Resuelvo la ecuación det_B = 0 en términos de lambda.

Sol = sp.solve(det_B, Lambda)

# Imprimo las soluciones

print('Sol =', Sol)

Sol = [0.0, 1.00000000000000, 2.00000000000000]


Luego, $\lambda = 0, 1, 2$.

# **Problemas de práctica:**

**Ejercicio 1:** Despejar $X$ en las ecuaciones matriciales.

(a). $3X - B^{T} = AX,$ donde

\

\begin{equation*}
 A =
\begin{pmatrix}
1 & 0 & -1\\
2 & 1 & 0\\
0 & 3 & 1
\end{pmatrix}, \
B =
\begin{pmatrix}
1 & 0 & 1
\end{pmatrix}.
\end{equation*} \


(b). $AX - 4X = CX +  I,$ donde

\

\begin{equation*}
 A =
\begin{pmatrix}
1 & 2 & 0\\
0 & 1 & 2\\
0 & 0 & 1
\end{pmatrix}, \ \
C =
\begin{pmatrix}
2 & -2 & 1\\
1 & 1 & -2\\
3 & 0 & 4
\end{pmatrix}.
\end{equation*}


In [ ]:
# Solución Ejercicio 1.

# (a):

In [ ]:
# Solución Ejercicio 1.

# (b):

**Ejercicio 2:** Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 k  & k^2 & 0\\
0 & k^3 & 4\\
-k & 0 & k
\end{pmatrix}.
\end{equation*} \

(a). Halle los valores de $k$ para los cuales la matriz $A$ no tiene inversa.


In [ ]:
# Solución Ejercicio 2.

# (a):

**Ejemplo 4:** Considere las matriz

\begin{equation*}
 A =
\begin{pmatrix}
 3 & 0 & 4\\
0 & -1 & 0\\
4 & 0 & 3
\end{pmatrix}.
\end{equation*} \

Determinar los valores de $\lambda$ tales que $det(A-\lambda I) = 0$.

In [ ]:
# Solución Ejercicio 3.

# (a):